ferremax/cart/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart, name='cart'),
     path('agregar', views.add, name='add'),
     path('eliminar', views.remove, name='remove'),
]

ferremax/ferremax/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

from django.conf import settings
from django.conf.urls.static import static

from django.urls import include

from products.views import ProductListView

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
    path('catalogo/', views.catalogo, name='catalogo'),
    path('ofertas/', views.ofertas, name='ofertas'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('carrito/', include('cart.urls')),
    path('productos/', ProductListView.as_view(), name='productos'),
    path('detalles/', include('products.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos', include('billing_profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ferremax/orders/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),
    path('pago', views.pay, name='pay')
]

ferremax/products/urls.py
from unicodedata import name
from urllib.parse import urlparse
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailview.as_view(), name='detalles'),
]

ferremax/cart/models.py
import uuid
import decimal

from django.db import models
from orders.common import OrderStatus

from users.models import User
from products.models import Product

from django.db.models.signals import pre_save
from django.db.models.signals import m2m_changed
from django.db.models.signals import post_save

class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE) #Posible error por el "On_Delete"
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    create_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.00 #Comision

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        if self.order:
            self.order.update_total()

    def update_subtotal(self):
        self.subtotal = sum( [ 
            cp.quantity * cp.product.price for cp in self.products_related()
         ] )
        self.save()

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()

    def products_related(self):
        return self.cartproducts_set.select_related('product')

    @property
    def order(self):
        return self.order_set.filter(status=OrderStatus.CREATED).first()


class CartProductsManager(models.Manager):

    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity

        object.update_quantity(quantity)
        return object

class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

ferremax/cart/views.py
from django.shortcuts import render
from products.models import Product
from .utils import get_or_create_cart
from .models import Cart
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from .models import CartProducts
 # Create your views here.

def cart(request):
    cart = get_or_create_cart(request)

    return render(request, 'cart/cart.html', {
        'cart': cart
    })

def add(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity', 1))

    # cart.products.add(product, through_defaults={
    #     'quantity': quantity
    # })

    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart, 
                                                                    product=product, 
                                                                    quantity=quantity)

    return render(request, 'cart/add.html', {
        'quantity': quantity,
        'cart_product': cart_product,
        'product':product
    })

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))

    cart.products.remove(product)

    return redirect('cart:cart')

ferremax/cart/templates/cart/add.html
{% load product_extras %}
{% load cart_extras %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://unpkg.com/nes.css/css/nes.css" rel="stylesheet" />
    <link rel="icon" href="">
    <link rel="stylesheet" href="{% static 'css/add.css'%}">
    <title>Se ha agregado con exito</title>
</head>
<body>

    <div class="nes-container with-title is-centered cuadro">
        <p class="title">Se ha agregado correctamente</p>
        <div class="nose">
            {% if product.image %}
            <img src="{{ product.image.url }}" alt="Imagen del producto" width="200" height="200">
            {% endif %}
            <div class="descripcion">
                {{ quantity | quantity_add_format }} al carrito
            </div>
            <div class="url">
                <a href="{% url 'products:detalles' product.slug %}">{{ product.title }}</a>
            </div>
            <div class="precio">
                {{ product.price | price_format }}
            </div>
            <div class="ver_carrito">
                <a href="{% url 'cart:cart' %}">Ver Carrito</a>
            </div>
        </div>
    </div>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
        Swal.fire({
            title: 'Un producto se ha añadido correctamente',
            showClass: {
                popup: 'animate__animated animate__fadeInDown'
            },
            hideClass: {
                popup: 'animate__animated animate__fadeOutUp'
            }
        })
</script>
</body>
</html>

ferremax/cart/templates/cart/cart.html
{% load product_extras %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://unpkg.com/nes.css/css/nes.css" rel="stylesheet" />
    <link rel="icon" href="">
    <link rel="stylesheet" href="{% static 'css/cart2.css'%}">
    <title>Carrito de Compras</title>
</head>
<header>
    <nav>
    <div class="nes-container is-dark with-title cabe">
        <p class="title">FERRE-MAX</p>
        <div class="loguito">
            <img src="../../../static/img/logo2.png" width="200" alt="Logo Empresa">
        </div>
        <div class="letras">
          <h2>Ferre-Max</h2>
        </div>
      </div>
    </nav>
    <br>
    <div class="nes-container is-rounded is-dark">
      <div class="head">
        <li><a href="{% url 'index' %}" class="nav-link px-2 link-secondary">Inicio</a></li>
        <li><a href="/contacto/" class="nav-link px-2 link-dark">Contactenos</a></li>
        <li><a href="{% url 'productos' %}" class="nav-link px-2 link-dark">Catalogo</a></li>
        <a href="/carrito/"><img class="nes-avatar is-rounded is-medium" alt="Carrito de compras" src="../../../static/img/cart.png" style="image-rendering: pixelated;"></a>
        <a href="/login/"><img alt="Iniciar sesion" class="nes-avatar is-large"  src="../.././static/img/Login2.png" style="image-rendering: pixelated;"></a>
        {% if request.user.is_authenticated %}
				<li><a href="{% url 'logout' %}">Logout</a></li>
				{% else %}
				{% endif %}
  </div>
    </div>
</header>
<body>
    <!-- Hacer un link a carrito de compras -->
    {% if cart.products.exists %}
    <div class="nes-table-responsive">
        <table class="nes-table is-bordered is-centered">
            <thead>
                <tr>
                    <th class="columnita1">Item</th>
                    <th class="columnita2">Imagen del producto</th>
                    <th class="columnita3">Producto</th>
                    <th class="columnita4">Cantidad</th>
                    <th class="columnita5">Precio</th>
                </tr>
            </thead>
            <tbody>
                {% for cp in cart.products_related %}
                {% with product=cp.product %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <th>
                        {% if product.image %}
                            <img src="{{ product.image.url }}" alt="Imagen del producto" width="120px" height="120px">
                        {% endif %}
                    </th>
                    <th>
                        <h2><a href="{% url 'products:detalles' product.slug %}">{{ product.title }}</a></h3>
                        {% include 'cart/snippets/remove.html' %}
                    </th>
                    <th>{{ cp.quantity }}</th>
                    <th>
                        <span class="a">{{ product.price | price_format }}</span>
                    </th>
                </tr>
                {% endwith %}
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="dos">
        <div class="precio">
            Subtotal({{ cart.products.count }}): <span>{{ cart.subtotal | price_format }}</span>
        </div>
        <div class="total">
            <a href="{% url 'orders:order' %}">Proceder al pago</a>
        </div>
        <div class="seguir">
            <a href="{% url 'productos' %}">Seguir comprando</a>
        </div>
    </div>
    {% else %}

    <div class="no_hay">
        <p>Tu carrito esta vacio.</p>
        <a href="{% url 'productos' %}">Seguir comprando</a>
        <img src="../../../static/img/dinosaur.png" width="120px" height="120px">
    </div>
    {% endif %}




    <footer>
        <br><br>
        <div class="pie">
        <p> ‎ ‎  </p>
        </div>
        <div class="caja">
          <img src="../../../static/img/logo2.png" alt="Logo">
            <p align="center">Si tienes alguna sugerencia que creas que puede aportar al proyecto puedes contactarme al este correo ferremax@gmail.com, estaré muy agradecido con tu feedback para continuar mejorando.</p>
            <div class="redes">
                <section class="icon-list">
                    <a href="https://www.facebook.com/profile.php?id=100081836352334"><i class="nes-icon facebook is-large contenido"></i></a>
                    <a href="https://www.instagram.com/ferremax707/"><i class="nes-icon instagram is-large contenido"></i></a>
                    <a href="mailto:ferremax707@gmail.com?Subject=Interesado%20en%20los%20Productos"><i class="nes-icon gmail is-large contenido"></i></a>
                    <a href="https://wa.link/6sxs6q"><i class="nes-icon whatsapp is-large contenido"></i></a>
                  </section>
                </div>
        </div>
    
        <div class="pie">
            <p> ‎ ‎  </p>
        </div>
    
        <div class="grupo">
            <i class="nes-icon is-medium heart"></i> <span class="nes-text is-error destacados">Grupo de Desarrollo WEB</span> <i class="nes-icon is-medium heart"></i>
          </div> 
    
        <div class="nosotros">
            <section class="nes-container is-dark member-card box"><div class="avatar"><img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Harri.png"></div> <div class="profile"><h4 class="name">‎ Harrison Fierro</h4> <p>‎ Desarrollador</p> <div class="iconos"><a href="https://github.com/Hfierro9" target="_blank" rel="noopener" aria-label="github"> <i class="nes-icon github is-medium"></i></a> <a href="mailto:alchemistnabi@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank" rel="noopener"><i class="nes-icon gmail is-medium"></i></a></div></div></section>
            <section class="nes-container is-dark member-card box"><div class="avatar"><img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Adrian.jpeg"></div> <div class="profile"><h4 class="name">‎ Adrian Martinez</h4> <p>‎ Desarrollador</p> <div class="iconos"><a href="https://github.com/AdrianMartinezzz" target="_blank" rel="noopener" aria-label="github"> <i class="nes-icon github is-medium"></i></a> <a href="mailto:adrianmartinezcontact@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank" rel="noopener"><i class="nes-icon gmail is-medium"></i></a></div></div></section>
            <section class="nes-container is-dark member-card box"><div class="avatar"><img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Frank.jpeg"></div> <div class="profile"><h4 class="name">‎ Franklin Suarez</h4> <p>‎ Desarrollador</p> <div class="iconos"><a href="https://github.com/fdsuarez413" target="_blank" rel="noopener" aria-label="github"> <i class="nes-icon github is-medium"></i></a> <a href="mailto:franklinsuarez904@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank" rel="noopener"><i class="nes-icon gmail is-medium"></i></a></div></div></section>
            <section class="nes-container is-dark member-card box"><div class="avatar"><img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Nicolas.png"></div> <div class="profile"><h4 class="name">‎ Nicolas Cifuen.</h4> <p>‎ Desarrollador</p> <div class="iconos"><a href="https://github.com/NicolasCifuentes2" target="_blank" rel="noopener" aria-label="github"> <i class="nes-icon github is-medium"></i></a> <a href="mailto:cifuentesbeltrann87@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank" rel="noopener"><i class="nes-icon gmail is-medium"></i></a></div></div></section>
        </div>
    </footer>
</body>

</html>