ferremax/billing_profiles/urls.py
from django.urls import path

from .import views

app_name = 'billing_profiles'

urlpatterns = [
    path('nuevo', views.create, name="create")
]

ferremax/cart/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart, name='cart'),
     path('agregar', views.add, name='add'),
     path('eliminar', views.remove, name='remove'),
]

ferremax/ferremax/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

from django.conf import settings
from django.conf.urls.static import static

from django.urls import include

from products.views import ProductListView

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
    path('catalogo/', views.catalogo, name='catalogo'),
    path('ofertas/', views.ofertas, name='ofertas'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('carrito/', include('cart.urls')),
    path('productos/', ProductListView.as_view(), name='productos'),
    path('detalles/', include('products.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos', include('billing_profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ferremax/orders/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),
    path('pago', views.pay, name='pay')
]

ferremax/shipping_addresses/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListview.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

ferremax/shipping_addresses/models.py
from django.db import models
from users.models import User
from enum import Enum
# Create your models here.

class ShippingAddres(models.Model): #Nombre erroneo
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    linea1 = models.CharField(max_length=200, verbose_name='Direccion 1')
    linea2 = models.CharField(max_length=200, blank=True, verbose_name='Direccion 2')
    city = models.CharField(max_length=100, verbose_name='Ciudad', default="Bogotá")
    state = models.CharField(max_length=100, verbose_name='Barrio')
    country = models.CharField(max_length=50, verbose_name='Pais', default="Colombia")
    reference = models.CharField(max_length=300, verbose_name='Anotacion')
    postal_code = models.CharField(max_length=10, null=False, blank=False, verbose_name='Codigo Postal')
    default = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.postal_code
    
    def has_orders(self):
        return self.order_set.count() >=1
    
    def update_default(self, default=False):
        self.default = default
        self.save()
    
    @property #Si hay error eliminar
    def address(self):
        return '{} - {} - {}'.format(self.country, self.city, self.state)

ferremax/shipping_addresses/forms.py
from django.forms import ModelForm
from .models import ShippingAddres

class ShippingAddressForm(ModelForm):
    class Meta:
        model = ShippingAddres
        fields = [
            'linea1', 'linea2', 'city', 'state', 'country', 'postal_code', 'reference'
        ]
        
        # labels= {
        #     'linea1': 'calle1',
        #     'linea2': 'calle1',
        #     'city': 'calle1',
        #     'state': 'calle1',
        #     'country': 'calle1',
        #     'postal_code':'Codigo postal',
        #     'reference':'Anotacion'
        # }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['linea1'].widget.attrs.update({
            'class':'form-control'
        })
        
        self.fields['linea2'].widget.attrs.update({
            'class':'form-control'
        })
        
        self.fields['city'].widget.attrs.update({
            'class':'form-control',
            'readonly':''
        })
        
        self.fields['state'].widget.attrs.update({
            'class':'form-control'
        })
        
        self.fields['country'].widget.attrs.update({
            'class':'form-control',
            'readonly':''
        })
        
        self.fields['postal_code'].widget.attrs.update({
            'class':'form-control',
            'placeholder': '111011.',
        })
        
        self.fields['reference'].widget.attrs.update({
            'class':'form-control',
            'placeholder': 'EJ: Casa, Apat.'
        })

ferremax/shipping_addresses/views.py
from audioop import reverse
from django.http import HttpResponseRedirect
from msilib.schema import ListView
from django.shortcuts import render
from django.views.generic import ListView
from cart.utils import get_or_create_cart
from .models import ShippingAddres
from .forms import ShippingAddressForm
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.shortcuts import reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from cart.utils import get_or_create_cart
from orders.utils import get_or_create_order
# Create your views here.


class ShippingAddressListview(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = ShippingAddres
    template_name = 'shipping_addresses/shipping_addresses.html'
    
    def get_queryset(self):
        return ShippingAddres.objects.filter(user=self.request.user).order_by('-default')

class ShippingAddressUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    login_url = 'login'
    model = ShippingAddres
    form_class = ShippingAddressForm
    template_name = 'shipping_addresses/update.html'
    success_message = 'Direccion Actualizada exitosamente'

    def get_success_url(self):
        return reverse('shipping_addresses:shipping_addresses')

    def dispatch(self, request, *args, **kwargs):
        if request.user.id != self.get_object().user_id:
            return redirect('cart:cart')
        
        return super(ShippingAddressUpdateView, self).dispatch(request, *args, **kwargs)
            
class ShippingAddressDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'login'
    model = ShippingAddres
    template_name = 'shipping_addresses/delete.html'
    success_url = reverse_lazy('shipping_addresses:shipping_addresses')

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().default:
            return redirect('shipping_addresses:shipping_addresses')
        
        if request.user.id != self.get_object().user_id:
            return redirect('cart:cart')
        
        if self.get_object().has_orders():
            return redirect('shipping_addresses:shipping_addresses')
     
        return super(ShippingAddressDeleteView, self).dispatch(request, *args, **kwargs)
        
@login_required(login_url='login')   
def create(request):
    form = ShippingAddressForm(request.POST or None)
    
    if request.method == 'POST' and form.is_valid():
        shipping_address = form.save(commit=False)
        shipping_address.user = request.user
        shipping_address.default = not request.user.has_shipping_address()
        
        shipping_address.save()
        
        if request.GET.get('next'):
            if request.GET['next'] == reverse('orders:address'):
                cart = get_or_create_cart(request)
                order = get_or_create_order(cart, request)
                
                order.update_shipping_address(shipping_address)
                
                return HttpResponseRedirect(request.GET['next'])
        
        messages.success(request, 'Direccion creada exitosamente')
        return redirect('shipping_addresses:shipping_addresses')
    
    return render(request, 'shipping_addresses/create.html', {
        'form':form
    })

@login_required(login_url='login')
def default(request, pk):
    shipping_address = get_object_or_404(ShippingAddres, pk=pk)

    if request.user.id != shipping_address.user_id:
        return redirect('cart:cart')

    if request.user.has_shipping_address():
        request.user.shipping_address.update_default()

    shipping_address.update_default(True)

    return redirect('shipping_addresses:shipping_addresses')

ferremax/shipping_addresses/templates/shipping_addresses/create.html
{% comment %} HTML importante {% endcomment %}

<div class="noc">
    Nueva Direccion
</div>
{% include 'shipping_addresses/snippets/form.html' with message='Crear' %}

ferremax/shipping_addresses/templates/shipping_addresses/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Direccion</title>
</head>
<body>
    
    <form method="post">
        {% csrf_token %}
        <p>¿Estas seguro de eliminar la dirección?</p>
        <input type="submit" value="Eliminar">
    </form>


</body>
</html>

ferremax/shipping_addresses/templates/shipping_addresses/shipping_addresses.html
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:create' as billing_profiles %}
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://unpkg.com/nes.css/css/nes.css" rel="stylesheet"/>
    <link rel="icon" href="">
    <link rel="stylesheet" href="{% static 'css/shippingadd1.css'%}">
    <title>FerreByte</title>
</head>
<header>
    <nav>
    <div class="nes-container is-dark with-title cabe">
        <p class="title">FERRE-MAX</p>
        <div class="loguito">
            <img src="../../../../../../static/img/logo2.png" width="200" alt="Logo Empresa">
        </div>
        <div class="letras">
          <h2>Ferre-Max</h2>
        </div>
      </div>
    </nav>
    <br>
    <div class="nes-container is-rounded is-dark">
      <div class="head">
        <li><a href="{% url 'index' %}" class="nav-link px-2 link-secondary">Inicio</a></li>
        <li><a href="/contacto/" class="nav-link px-2 link-dark">Contactenos</a></li>
        <li><a href="{% url 'productos' %}" class="nav-link px-2 link-dark">Catalogo</a></li>
        <a href="/carrito/"><img class="nes-avatar is-rounded is-medium" alt="Carrito de compras" src="../../../static/img/cart.png" style="image-rendering: pixelated;"></a>
        <a href="/login/"><img alt="Iniciar sesion" class="nes-avatar is-large"  src="../../../static/img/Login2.png" style="image-rendering: pixelated;"></a>
        {% if request.user.is_authenticated %}
  </div>
    </div>
    <br>
    <h2 align="center">Mi perfil - {{ user.username }}</h2>
    <div class="nes-container is-rounded is-dark">
      <div class="head">
        <li><a href="{{ completeds }}">Mis pedidos</a></li>
        <li><a href="/direcciones/">Mis direcciones</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </div>
    </div>
    {% else %}
    {% endif %}
</header>
<body>
  
  {% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}">
      <button type="button" class="close" data-dismiss="alert">x</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

<div class="nes-container with-title is-centered cuadro">
  <p class="title">Mis direcciones</p>
<div class="add">
    <a href="{% url 'shipping_addresses:create' %}">Agregar nueva direccion</a>
</div>

<div class="midireccion">
    {% for shipping_address in object_list %}
        {% include 'shipping_addresses/snippets/shipping_addresses.html' with edit=True %}
    {% endfor %}
</div>
</div>







<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>







<footer>
  <br><br>
  <div class="pie">
  <p> ‎ ‎  </p>
  </div>
  <div class="caja">
    <img src="../../../static/img/logo2.png" alt="Logo">
      <p align="center">Si tienes alguna sugerencia que creas que puede aportar al proyecto puedes contactarme al este correo ferremax@gmail.com, estaré muy agradecido con tu feedback para continuar mejorando.</p>
      <div class="redes">
          <section class="icon-list">
              <a href="https://www.facebook.com/profile.php?id=100081836352334"><i class="nes-icon facebook is-large contenido"></i></a>
              <a href="https://www.instagram.com/ferremax707/"><i class="nes-icon instagram is-large contenido"></i></a>
              <a href="mailto:ferremax707@gmail.com?Subject=Interesado%20en%20los%20Productos"><i class="nes-icon gmail is-large contenido"></i></a>
              <a href="https://wa.link/6sxs6q"><i class="nes-icon whatsapp is-large contenido"></i></a>
            </section>
          </div>
  </div>

  <div class="pie">
      <p> ‎ ‎  </p>
  </div>

  <div class="grupo">
    <i class="nes-icon is-medium heart"></i> <span class="nes-text is-error destacados">Grupo de Desarrollo WEB</span> <i class="nes-icon is-medium heart"></i>
  </div> 

  <div class="nosotros">
      <section class="nes-container is-dark member-card box"><div class="avatar"><img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Harri.png"></div> <div class="profile"><h4 class="name">‎ Harrison Fierro</h4> <p>‎ Desarrollador</p> <div class="iconos"><a href="https://github.com/Hfierro9" target="_blank" rel="noopener" aria-label="github"> <i class="nes-icon github is-medium"></i></a> <a href="mailto:alchemistnabi@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank" rel="noopener"><i class="nes-icon gmail is-medium"></i></a></div></div></section>
      <section class="nes-container is-dark member-card box"><div class="avatar"><img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Adrian.jpeg"></div> <div class="profile"><h4 class="name">‎ Adrian Martinez</h4> <p>‎ Desarrollador</p> <div class="iconos"><a href="https://github.com/AdrianMartinezzz" target="_blank" rel="noopener" aria-label="github"> <i class="nes-icon github is-medium"></i></a> <a href="mailto:adrianmartinezcontact@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank" rel="noopener"><i class="nes-icon gmail is-medium"></i></a></div></div></section>
      <section class="nes-container is-dark member-card box"><div class="avatar"><img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Frank.jpeg"></div> <div class="profile"><h4 class="name">‎ Franklin Suarez</h4> <p>‎ Desarrollador</p> <div class="iconos"><a href="https://github.com/fdsuarez413" target="_blank" rel="noopener" aria-label="github"> <i class="nes-icon github is-medium"></i></a> <a href="mailto:franklinsuarez904@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank" rel="noopener"><i class="nes-icon gmail is-medium"></i></a></div></div></section>
      <section class="nes-container is-dark member-card box"><div class="avatar"><img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Nicolas.png"></div> <div class="profile"><h4 class="name">‎ Nicolas Cifuen.</h4> <p>‎ Desarrollador</p> <div class="iconos"><a href="https://github.com/NicolasCifuentes2" target="_blank" rel="noopener" aria-label="github"> <i class="nes-icon github is-medium"></i></a> <a href="mailto:cifuentesbeltrann87@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank" rel="noopener"><i class="nes-icon gmail is-medium"></i></a></div></div></section>
  </div>
</footer>

</body>

ferremax/shipping_addresses/templates/shipping_addresses/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Direccion</title>
</head>
<body>
    
    <h3>Editar Dirección</h3>

    {% include 'shipping_addresses/snippets/form.html' with message='Actualizar' %}

</body>
</html>