ferremax/cart/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
     path('', views.cart, name='cart'),
     path('agregar', views.add, name='add'),
     path('eliminar', views.remove, name='remove'),
]

ferremax/ferremax/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

from django.conf import settings
from django.conf.urls.static import static

from django.urls import include

from products.views import ProductListView

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
    path('catalogo/', views.catalogo, name='catalogo'),
    path('ofertas/', views.ofertas, name='ofertas'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('carrito/', include('cart.urls')),
    path('productos/', ProductListView.as_view(), name='productos'),
    path('detalles/', include('products.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos', include('billing_profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ferremax/orders/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),
    path('pago', views.pay, name='pay')
]

ferremax/promo_codes/urls.py
from django.urls import path

from .import views

app_name = 'promo_codes'

urlpatterns = [
    path('validar', views.validate, name="validate")
]

ferremax/shipping_addresses/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListview.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

ferremax/orders/models.py
from django.db import models
from promo_codes.models import PromoCode
from shipping_addresses.models import ShippingAddres
from users.models import User
from cart.models import Cart
from django.db.models.signals import pre_save
import uuid
from .common import OrderStatus
from .common import choices
import decimal
# Create your models here.


class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices, default=OrderStatus.CREATED)
    shipping_total = models.DecimalField(default=0, max_digits=8, decimal_places=0)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddres, null=True, blank=True, on_delete=models.CASCADE)
    promo_code = models.OneToOneField(PromoCode, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id
    
    def apply_promo_code(self, promo_code):
        if self.promo_code is None:
            self.promo_code = promo_code
            self.save()
            
            self.update_total()
            promo_code.use()
    
    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
        
        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)
            
        return shipping_address

    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()

    def update_total(self):
        self.total = self.get_total()
        self.save()

    def get_discount(self):
        if self.promo_code:
            return self.promo_code.discount
        
        return 0

    def get_total(self):
        return self.cart.total + self.shipping_total - decimal.Decimal(self.get_discount())

def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *arg, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

ferremax/orders/views.py
from concurrent.futures import thread
from django.shortcuts import render
from cart.utils import get_or_create_cart
from shipping_addresses.models import ShippingAddres
from .utils import get_or_create_order
from django.contrib.auth.decorators import login_required
from .utils import breadcrumb
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib import messages
from .utils import destroy_order
from cart.utils import destroy_cart
from .mails import Mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.db.models.query import EmptyQuerySet
from .decorators import validate_cart_and_order
import threading

# Create your views here.

class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = 'orders/orders.html'
    
    def get_queryset(self):
        return self.request.user.orders_completed()
    
    

@login_required(login_url='login')
@validate_cart_and_order
def order(request, cart, order):
    return render(request, 'orders/order.html', {
        'cart': cart,
        'order': order,
        'breadcrumb': breadcrumb()
    })

@login_required(login_url='login')
@validate_cart_and_order
def address(request, cart, order):
    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.has_shipping_addresses()
    
    return render(request, 'orders/address.html', {
        'cart': cart,
        'order': order,
        'shipping_address':shipping_address,
        'can_choose_address':can_choose_address,
        'breadcrumb': breadcrumb(address=True)
    })

def pay(request):
    return render(request, 'orders/pay.html', {
        'breadcrumb': breadcrumb(address=True)
    })


@login_required(login_url='login')   
def select_address(request):
    shipping_addresses = request.user.addresses
    
    return render(request, 'orders/select_address.html', {
        'breadcumb': breadcrumb(address=True),
        'shipping_addresses':shipping_addresses
    })

@login_required(login_url='login')
@validate_cart_and_order
def check_address(request, cart, order, pk):
    shipping_address = get_object_or_404(ShippingAddres, pk=pk)
    
    if request.user.id != shipping_address.user_id:
        return redirect('cart:cart')
    
    order.update_shipping_address(shipping_address)
    
    return redirect('orders:address')

@login_required(login_url='login')
@validate_cart_and_order
def confirm(request, cart, order,): 
    shipping_address = order.shipping_address
    
    if shipping_address is None:
        return redirect('orders:address')
    
    return render(request, 'orders/confirm.html', {
        'cart': cart,
        'order': order,
        'shipping_address': shipping_address,
        'breadcrumb':breadcrumb(address=True, confirmation=True),
    })

@login_required(login_url='login')
@validate_cart_and_order
def cancel(request, cart, order): 
    if request.user.id != order.user_id:
        return redirect('cart:cart')
    
    order.cancel()
    
    destroy_cart(request)
    destroy_order(request)
    
    messages.error(request, 'Orden cancelada')
    return redirect('index') #Mirar mensaje

@login_required(login_url='login')
@validate_cart_and_order
def complete(request, cart, order):  
    if request.user.id != order.user_id:
        return redirect('cart:cart')
    
    order.complete()
    
    thread = threading.Thread(target=Mail.send_complete_order, args=(
        order, request.user
    )) 
    
    thread.start()
    
    destroy_cart(request)
    destroy_order(request)
    
    messages.success(request, 'Compra completada Exitosamente')
    return redirect('index')

ferremax/orders/templates/orders/address.html
{% url 'orders:completeds' as completeds %}
{% load static %}
{% url 'orders:pago' as pago %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet" />
  <link href="https://unpkg.com/nes.css/css/nes.css" rel="stylesheet" />
  <link rel="icon" href="" />
  <link rel="stylesheet" href="{% static 'css/address.css'%}" />
  <title>FerreByte</title>
</head>
<header>
  <nav>
    <div class="nes-container is-dark with-title cabe">
      <p class="title">FERRE-MAX</p>
      <div class="loguito">
        <img src="../../../static/img/logo2.png" width="200" alt="Logo Empresa" />
      </div>
      <div class="letras">
        <h2>Ferre-Max</h2>
      </div>
    </div>
  </nav>
  <br />
  <div class="nes-container is-rounded is-dark">
    <div class="head">
      <li>
        <a href="{% url 'index' %}" class="nav-link px-2 link-secondary">Inicio</a>
      </li>
      <li>
        <a href="/contacto/" class="nav-link px-2 link-dark">Contactenos</a>
      </li>
      <li>
        <a href="{% url 'productos' %}" class="nav-link px-2 link-dark">Catalogo</a>
      </li>
      <a href="/carrito/"><img class="nes-avatar is-rounded is-medium" alt="Carrito de compras"
          src="../../../static/img/cart.png" style="image-rendering: pixelated" /></a>
      <a href="/login/"><img alt="Iniciar sesion" class="nes-avatar is-large" src="../../../static/img/Login2.png"
          style="image-rendering: pixelated" /></a>
      {% if request.user.is_authenticated %}
    </div>
  </div>
  <br />
  <h2 align="center">Mi perfil</h2>
  <div class="nes-container is-rounded is-dark">
    <div class="head">
      <li><a href="{{ completeds }}">Mis pedidos</a></li>
      <li><a href="/direcciones/">Mis direcciones</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
    </div>
  </div>
  {% else %} {% endif %}
</header>

<body>
  <div class="nes-container with-title pasos">
    {% include 'orders/snippets/breadcrumb.html' %}
    <hr />
    <div class="noce4">
      {% if shipping_address %}
      <div class="noce5">
        <p align="center">Recoge el pedido en el punto de entrega</p>
      </div>
      <div class="cuadrito-direccion">
        <div class="nes-container with-title is-centered">
          {% include 'shipping_addresses/snippets/shipping_addresses.html' %}
          {% if can_choose_address %}
          <div class="nose9">
            <a href="{% url 'orders:select_address' %}">Otra Direccion</a>
          </div>
          {% endif %}
          <a href="{% url 'orders:pay' %}">Entregar a esta direccion</a>
        </div>
      </div>
      {% else %}

      <div class="no-direccion">
        <div class="Nueva">
          <p>Registra tu direccion de envio</p>
        </div>
        <div class="Registrar">
          {% url 'orders:address' as next_url %}
          <a href="{% url 'shipping_addresses:create' %}?next={{ next_url }}" class="nes-badge">
            <span class="is-error">Nueva Direccion de envio</span>
          </a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>

  <footer>
    <br /><br />
    <div class="pie">
      <p>‎ ‎</p>
    </div>
    <div class="caja">
      <img src="static/img/logo2.png" alt="Logo" />
      <p align="center">
        Si tienes alguna sugerencia que creas que puede aportar al proyecto
        puedes contactarme al este correo ferremax@gmail.com, estaré muy
        agradecido con tu feedback para continuar mejorando.
      </p>
      <div class="redes">
        <section class="icon-list">
          <a href="https://www.facebook.com/profile.php?id=100081836352334"><i
              class="nes-icon facebook is-large contenido"></i></a>
          <a href="https://www.instagram.com/ferremax707/"><i class="nes-icon instagram is-large contenido"></i></a>
          <a href="mailto:ferremax707@gmail.com?Subject=Interesado%20en%20los%20Productos"><i
              class="nes-icon gmail is-large contenido"></i></a>
          <a href="https://wa.link/6sxs6q"><i class="nes-icon whatsapp is-large contenido"></i></a>
        </section>
      </div>
    </div>

    <div class="pie">
      <p>‎ ‎</p>
    </div>

    <div class="grupo">
      <i class="nes-icon is-medium heart"></i>
      <span class="nes-text is-error destacados">Grupo de Desarrollo WEB</span>
      <i class="nes-icon is-medium heart"></i>
    </div>

    <div class="nosotros">
      <section class="nes-container is-dark member-card box">
        <div class="avatar">
          <img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Harri.png" />
        </div>
        <div class="profile">
          <h4 class="name">‎ Harrison Fierro</h4>
          <p>‎ Desarrollador</p>
          <div class="iconos">
            <a href="https://github.com/Hfierro9" target="_blank" rel="noopener" aria-label="github">
              <i class="nes-icon github is-medium"></i></a>
            <a href="mailto:alchemistnabi@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank"
              rel="noopener"><i class="nes-icon gmail is-medium"></i></a>
          </div>
        </div>
      </section>
      <section class="nes-container is-dark member-card box">
        <div class="avatar">
          <img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Adrian.jpeg" />
        </div>
        <div class="profile">
          <h4 class="name">‎ Adrian Martinez</h4>
          <p>‎ Desarrollador</p>
          <div class="iconos">
            <a href="https://github.com/AdrianMartinezzz" target="_blank" rel="noopener" aria-label="github">
              <i class="nes-icon github is-medium"></i></a>
            <a href="mailto:adrianmartinezcontact@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank"
              rel="noopener"><i class="nes-icon gmail is-medium"></i></a>
          </div>
        </div>
      </section>
      <section class="nes-container is-dark member-card box">
        <div class="avatar">
          <img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Frank.jpeg" />
        </div>
        <div class="profile">
          <h4 class="name">‎ Franklin Suarez</h4>
          <p>‎ Desarrollador</p>
          <div class="iconos">
            <a href="https://github.com/fdsuarez413" target="_blank" rel="noopener" aria-label="github">
              <i class="nes-icon github is-medium"></i></a>
            <a href="mailto:franklinsuarez904@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank"
              rel="noopener"><i class="nes-icon gmail is-medium"></i></a>
          </div>
        </div>
      </section>
      <section class="nes-container is-dark member-card box">
        <div class="avatar">
          <img width="80px" alt="Miembro de Desarrollo" class="imgRedonda" src="../../../static/img/Nicolas.png" />
        </div>
        <div class="profile">
          <h4 class="name">‎ Nicolas Cifuen.</h4>
          <p>‎ Desarrollador</p>
          <div class="iconos">
            <a href="https://github.com/NicolasCifuentes2" target="_blank" rel="noopener" aria-label="github">
              <i class="nes-icon github is-medium"></i></a>
            <a href="mailto:cifuentesbeltrann87@gmail.com?Subject=Interesado%20en%20el%20Desarrollo" target="_blank"
              rel="noopener"><i class="nes-icon gmail is-medium"></i></a>
          </div>
        </div>
      </section>
    </div>
  </footer>
</body>

</html>

ferremax/orders/templates/orders/confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://unpkg.com/nes.css/css/nes.css" rel="stylesheet" />
    <link rel="icon" href="">
    <link rel="stylesheet" href="{% static 'css/confirm.css'%}">
    <title>Orden de Compra</title>
</head>
<header>
    <nav>
    <div class="nes-container is-dark with-title cabe">
        <p class="title">FERRE-MAX</p>
        <div class="loguito">
            <img src="../../../static/img/logo2.png" width="200" alt="Logo Empresa">
        </div>
        <div class="letras">
          <h2>Ferre-Max</h2>
        </div>
      </div>
    </nav>
    <br>
    <div class="nes-container is-rounded is-dark">
      <div class="head">
        <li><a href="{% url 'index' %}" class="nav-link px-2 link-secondary">Inicio</a></li>
        <li><a href="/contacto/" class="nav-link px-2 link-dark">Contactenos</a></li>
        <li><a href="{% url 'productos' %}" class="nav-link px-2 link-dark">Catalogo</a></li>
        <a href="/carrito/"><img class="nes-avatar is-rounded is-medium" alt="Carrito de compras" src="../../../static/img/cart.png" style="image-rendering: pixelated;"></a>
        <a href="/login/"><img alt="Iniciar sesion" class="nes-avatar is-large"  src="../../../static/img/Login2.png" style="image-rendering: pixelated;"></a>
        {% if request.user.is_authenticated %}
  </div>
    </div>
    <br>
    <h2 align="center">Mi perfil</h2>
    <div class="nes-container is-rounded is-dark">
      <div class="head">
        <li><a href="{{ completeds }}">Mis pedidos</a></li>
        <li><a href="/direcciones/">Mis direcciones</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </div>
    </div>
    {% else %}
    {% endif %}
</header>
<body>
    
    {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}">
        <button type="button" class="close" data-dismiss="alert">x</button>
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

    <div class="cru">
        {% include 'orders/snippets/breadcrumb.html' %}
    </div>

    <div class="">
        <h3 align="center">Confirma tu pedido</h3>
    </div>
    <div class="envio">
        
    </div>
    <div class="todo_titulos">
        <div class="envio nes-container">
            <div class="">
                <strong class="palabra">Direccion de envio</strong>
            </div>
            <div class="">
                {{ shipping_address.linea1 }}
            </div>
            <div class="">
                {{ shipping_address.state }}
            </div>
            <div class="">
                {{ shipping_address.reference }}
            </div>
            <div class="">
                {{ shipping_address.postal_code }}
            </div>
        </div>
        <div class="pago nes-container">
            <div class="">
                <strong class="palabra">Metodo de pago</strong>
            </div>
            <div class="pago2">
                <p align="center">Pago contraEntrega</p>
            </div>
        </div>
        <div class="codigo nes-container">
            <div class="">
                <strong class="palabra">Código promocional</strong>
            </div>
            <form id="promocode-form" action="{% url 'promo_codes:validate' %}">
                <input type="text" name="code" value="{{ order.promo_code.code }}" class="nes-input is-success" placeholder="Codigo promocion" {% if order.promo_code %} readonly {% endif %}>
            </form>
            <div class="" id="promocode-success">
                {% if order.promo_code %}
                    <p align="center">Codigo aplicado exitosamente</p>
                {% endif %}
                <!-- Mirar la clase correcta -->
            </div>
        </div>
    </div>

    <div class="">
        {% for product in cart.products.all %}
            {% include 'orders/snippets/product.html' %}
        {% endfor %}
    </div>

    
        {% url 'orders:complete' as next_url %}
        {% include 'orders/snippets/resume.html' with next_url=next_url %}
    <div class="botones">
        <a class="nes-btn is-error" href="{% url 'orders:cancel' %}">Cancelar orden</a>
    </div>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


<script>

    const form = document.getElementById('promocode-form')

    form.addEventListener('submit', function(e){
        e.preventDefault()
        
        const input = this.code
        const code = input.value
        const url = this.action +"?code=" + code
        const div_total = document.getElementById('order-total')
        const div_success = document.getElementById("promocode-success")

        fetch(url)
            .then(response => response.json())
            .then(response => {
                console.log(response.total)

                if(response.status === true){

                    div_total.innerHTML = "$" + response.total

                    div_success.classList.remove('noce22-daner')
                    div_success.classList.remove('noce22')

                    div_success.innerHTML = 'Codigo aplicado exitosamente'

                    input.readOnly = true

                }else{
                    div_success.innerHTML = 'Codigo no valido'
                    div_success.classList.remove('noce22')
                    div_success.classList.remove('noce22-danger')
                }
            })

        
    })

</script>

</html>

ferremax/orders/templates/orders/orders.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://unpkg.com/nes.css/css/nes.css" rel="stylesheet" />
    <link rel="icon" href="">
    <link rel="stylesheet" href="{% static 'css/misped1.css'%}">
    <title>Orden de Compra</title>
</head>
<header>
  <nav>
  <div class="nes-container is-dark with-title cabe">
      <p class="title">FERRE-MAX</p>
      <div class="loguito">
          <img src="../../../../../../static/img/logo2.png" width="200" alt="Logo Empresa">
      </div>
      <div class="letras">
        <h2>Ferre-Max</h2>
      </div>
    </div>
  </nav>
  <br>
  <div class="nes-container is-rounded is-dark">
    <div class="head">
      <li><a href="{% url 'index' %}" class="nav-link px-2 link-secondary">Inicio</a></li>
      <li><a href="/contacto/" class="nav-link px-2 link-dark">Contactenos</a></li>
      <li><a href="{% url 'productos' %}" class="nav-link px-2 link-dark">Catalogo</a></li>
      <a href="/carrito/"><img class="nes-avatar is-rounded is-medium" alt="Carrito de compras" src="../../../static/img/cart.png" style="image-rendering: pixelated;"></a>
      <a href="/login/"><img alt="Iniciar sesion" class="nes-avatar is-large"  src="../../../static/img/Login2.png" style="image-rendering: pixelated;"></a>
      {% if request.user.is_authenticated %}
</div>
  </div>
  <br>
  <h2 align="center">Mi perfil - {{ user.username }}</h2>
  <div class="nes-container is-rounded is-dark">
    <div class="head">
      <li><a href="{{ completeds }}">Mis pedidos</a></li>
      <li><a href="/direcciones/">Mis direcciones</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
    </div>
  </div>
  {% else %}
  {% endif %}
</header>
<body>
    
    <div class="pedidos">
        <p align="center">Mis pedidos</p>
    </div>
    <div class="lista ">
        {% for order in object_list %}
            {% include 'orders/snippets/order.html' %}
        {% endfor %}
    </div>



</body>
</html>

ferremax/orders/templates/orders/pay.html
{% load static %}
{% url 'orders:completeds' as completeds %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://unpkg.com/nes.css/css/nes.css" rel="stylesheet" />
    <link rel="icon" href="">
    <link rel="stylesheet" href="{% static 'css/pay.css'%}">
    <title>Pagos</title>
</head>
<header>
  <nav>
  <div class="nes-container is-dark with-title cabe">
      <p class="title">FERRE-MAX</p>
      <div class="loguito">
          <img src="../../../../../../static/img/logo2.png" width="200" alt="Logo Empresa">
      </div>
      <div class="letras">
        <h2>Ferre-Max</h2>
      </div>
    </div>
  </nav>
  <br>
  <div class="nes-container is-rounded is-dark">
    <div class="head">
      <li><a href="{% url 'index' %}" class="nav-link px-2 link-secondary">Inicio</a></li>
      <li><a href="/contacto/" class="nav-link px-2 link-dark">Contactenos</a></li>
      <li><a href="{% url 'productos' %}" class="nav-link px-2 link-dark">Catalogo</a></li>
      <a href="/carrito/"><img class="nes-avatar is-rounded is-medium" alt="Carrito de compras" src="../../../static/img/cart.png" style="image-rendering: pixelated;"></a>
      <a href="/login/"><img alt="Iniciar sesion" class="nes-avatar is-large"  src="../../../static/img/Login2.png" style="image-rendering: pixelated;"></a>
      {% if request.user.is_authenticated %}
</div>
  </div>
  <br>
  <h2 align="center">Mi perfil - {{ user.username }}</h2>
  <div class="nes-container is-rounded is-dark">
    <div class="head">
      <li><a href="{{ completeds }}">Mis pedidos</a></li>
      <li><a href="/direcciones/">Mis direcciones</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
    </div>
  </div>
  {% else %}
  {% endif %}
</header>
<body>
    
    <br>
    {% include 'orders/snippets/breadcrumb.html' %}

    <br>
    <br>
    <h1 align="center">Tenga en cuenta:</h1>
    <div class="duda">
        <p align="center">Todas las compras que usted realice seran pagadas el mismo día de la entrega, ya que no contamos con otros medios de pagos, si tiene alguna duda, contactenos.</p>
    </div>

    <div class="boton">
        <a class="nes-btn is-success" href="{% url 'orders:confirm' %}">Confirmacion</a>
    </div>

</body>
</html>

ferremax/orders/templates/orders/select_address.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seleccione su direccion</title>
</head>
<body>

    {% include 'orders/snippets/breadcrumb.html' %}

    <div class="nose7">
        <h3>Selecciona una direccion de envio</h3>
    </div>
    <div class="nose8">
        {% for shipping_address in shipping_addresses %}
            <div class="nose9">
                <h5>{{ shipping_address.address }}</h5>
                <p>{{ shipping_address.postal_code }}</p>
                <a href="{% url 'orders:check_address' shipping_address.pk %}">
                    Seleccionar
                </a>
            </div>
        {% endfor %}
    </div>

</body>
</html>